### ISSUE TITLE
Gate can't detect IC2 Reactor contents

### ISSUE THREAD

**Issue by Flexico** [BuildCraft/BuildCraft#2193]
When i have a gate next to a reactor, even if the inventory is full, the "inventory full" option doesn't respond. I've tried it on reactors with 0 extra chambers all the way up to the maximum 6 and it never works.

Same issue on both BC 6.1.7 and 6.0.18 with IC2 2.2.650

**Comment by M111C** [comment]
Hello @asiekierka, i can see that it's been over a year since this problem was mentioned, but it's still not working.
I know it's probably as much IC2's fault, but this is the only thing keeping me from fully automating my reactors.
the problem is that the neutron reflectors i use in the reators just vanish, when used up, otherwise i coud just pull them out, and send a detection signal, but i really need to know when they disapear, and there is space in the reactor...
I'm not sure if it's only bugging in the fluid reactors..
Anyway, i just wanted to mention it :)

**Comment by Speiger** [comment]
Use my Pipe Additions mod. That allows you to control slots specialy. I suggested that to BC but asies answer was: Nope...
@M111C

**Comment by M111C** [comment]
@Speiger 
Cool, thanks a lot :D

**Comment by M111C** [comment]
@Speiger Hey, I can't find your mod on here. I was going to report a problem on Buildcraft forum, but it's gone 502...

**Comment by asiekierka** [comment]
Fixed.

Dnia 10 lis 2015 o godz. 11:52 M111C <notifications@github.com> napisał(a):

**Comment by M111C** [comment]
@asiekierka 
oh, cool. Is the update released yet, and what is the excact version?
I'll be happy to test this out.

**Comment by asiekierka** [comment]
Oh, sorry, no. The forum is the thing fixed.

Dnia 10 lis 2015 o godz. 13:15 M111C <notifications@github.com> napisał(a):

**Comment by AEnterprise** [comment]
should be fixed

**Comment by Speiger** [comment]
@AEnterprise did you test that with IC2 Exp? If not then its not fixed.

**Comment by AEnterprise** [comment]
not personaly no but i have a friend who uses a gate on FTB infinity evolved skyblock to automate his reactor

**Comment by Speiger** [comment]
@AEnterprise does that include a FullReactor or a Partially build reactor?
Also there are differences between classic & exp inventories...

**Comment by AEnterprise** [comment]
i duno i'll ask but the pack uses ic2 exp

**Comment by AEnterprise** [comment]
should be no problem with the new inventory capabilities

**Comment by Flexico** [comment]
I'm using Experimental #825 and it works now! Just to clarify. ^^
