### ISSUE TITLE
Planter Robot will not plant sapling types from the Forestry mod

### ISSUE THREAD

**Issue by chemdork123** [BuildCraft/BuildCraft#3182]
The planter robot does not plant saplings from the forestry mod.  The same behavior is observed regardless of whether or not the samplings have been analyzed via the treealyzer (from forestry).

Planter robots will pick up saplings that are from vanilla minecraft *or* forestry via a load/unload in area command; however, only the vanilla minecraft saplings are planted by the robot in the work in area location.  For forestry saplings, the robot goes to the station to retrieve the sapling, the sapling is picked up and the robot "holds" it, then after a short time (less than a minute), the robot returns to home--still holding the forestry sapling--indefinitely.

This issue might be related to #3030 ... ??

**Comment by psxlover** [comment]
What version of buildcraft compat are you using?

**Comment by chemdork123** [comment]
Sorry version information *(I'm using minecraft + buildcraft, thermal expansion, forestry, and NEI)*:

MC: 1.7.10
Forge: 10.13.4.1558
Buildcraft: 7.1.14
Buildcraft compat: 7.1.3
Forestry: 3.6.7.25

**Comment by LuigiHutch** [comment]
https://github.com/BuildCraft/BuildCraft/issues/2561

**Comment by AEnterprise** [comment]
alright so BCC 7.1.x doesn't add support then

**Comment by hea3ven** [comment]
I thought this was fixed in forestry side, maybe in forestry 4.

**Comment by chemdork123** [comment]
Yeah, send the same issue as #2561 .  It seems it's not quite fixed?...

**Comment by LuigiHutch** [comment]
This issues also happens with Forestry 4.2.4

**Comment by chemdork123** [comment]
Also confirmed it happens with forestry 4.2.4.

**Comment by chemdork123** [comment]
So is this an issue that isn't fixable on BC side because of how forestry handles their saplings?

**Comment by asiekierka** [comment]
We tried to fix it with BuildCraftCompat once, not sure what happened to
that and apparently neither of the devs have time to look into it. Very
sorry.

2016-03-14 15:53 GMT+01:00 chemdork123 <notifications@github.com>:

**Comment by asiekierka** [comment]
@chemdork123 - I just re-checked. With BuildcraftCompat 7.1.3, Forestry 4.2.10 and BuildCraft 7.1.x it seems to work just fine.

Perhaps you need Forestry 4.x?

**Comment by asiekierka** [comment]
Yes. It seems to work fine with BuildCraft 7.1.8, *not* 7.1.15! So what this is is a *regression*! Let's fix it!

**Comment by asiekierka** [comment]
Truly, truly sorry for how long this took to fix, @chemdork123 .

https://github.com/BuildCraft/BuildcraftCompat/commit/0e78cce8fd52b2a956dcf1361277cb737e597c75

**Comment by chemdork123** [comment]
No problem, @asiekierka , it's just awesome that it's fixed now!  Really appreciate looking into this.

**Comment by chemdork123** [comment]
Incidentally, how difficult would it be to make the planter robots "smart" enough to know to plant saplings in a 2x2 or 3x3 pattern based on the type of sapling?  i.e. - be able to function with Dark Oak saplings or the various wide-trunk sapling types from forestry and other mods?

**Comment by asiekierka** [comment]
We cannot tell them apart, however thanks for noticing this - I'll ponder
on it.

2016-03-18 15:54 GMT+01:00 chemdork123 <notifications@github.com>:

**Comment by AEnterprise** [comment]
maybe a gate action to make the robot plant in squares with a param to set it to 2x2 or 3x3?

**Comment by chemdork123** [comment]
@AEnterprise , this is a good idea (if it is possible to implement).  This way you leave the decision of the formation of sapling planting up to the user, and not based on the sapling.  Would you think it's easier to have the robot pick up 4 or 9 saplings (instead of one at a time) and plant them together, or have them pick up one at a time and plant in the different pattern?

From the user side, any implementation like this seems useful and usable..

**Comment by asiekierka** [comment]
Features are paused until BuildCraft 8.0 hits, as it will invalidate or
require changes to a lot of the proposals.

Unless I give up again and 8.0 becomes vaporware (again).

2016-03-18 17:39 GMT+01:00 chemdork123 <notifications@github.com>:

**Comment by hea3ven** [comment]
If the zone mapper could zoom enough to select block by block the user could just set up multiple 2x2 areas.

Another thing that could be easily done, and I think is a good change, is to make the robots add up all the active working zones. Right now they just use the first one they find in the gate.

**Comment by asiekierka** [comment]
@chemdork123 - Do you have some sort of Skype/IM/e-mail contact, by the way? I'd like to discuss some future BuildCraft plans with you.

**Comment by chemdork123** [comment]
@asiekierka easiest way to reach me is chemdork123@gmail.com .  I'm not on Skype very often.  Love to help out.

**Comment by Amelia-** [comment]
@hea3ven you can do that with the zone planner, it's a little tedious to do for large areas but it works.
I think it also works if you make an area or grid with stone or something else they won't plant saplings on and fill the spaces where you want them to plant saplings with dirt and then just mark the entire area with the zone planner.
