### ISSUE TITLE
Crash on Dedicated Server With Sponge

### ISSUE THREAD

**Issue by kenijey** [BuildCraft/BuildCraft#3594]
[crash-2017-05-20_15.46.51-server.txt](https://github.com/BuildCraft/BuildCraft/files/1016167/crash-2017-05-20_15.46.51-server.txt)
i used sponge 2343. please help.
mc 1.11.2

**Comment by kenijey** [comment]
and plz tell me if i should report it to sponge

**Comment by AlexIIL** [comment]
Please do - while I think its something that probably needs to be changed in BuildCraft, it would be helpful for someone from sponge to clarify exactly what we're doing wrong here.

**Comment by AEnterprise** [comment]
@AlexIIL from what i know from it this is them catching events ment for logging and reverting (as part of grief protection plugins) and apearently they are doing a sanity check on the world UUID (not sure why, guess they are also logging/using it somewhere)

i think we might want to talk to them about some kind of fixed UUID or flag that mods can put on worlds to make them excluded from these kinds as players can't possibly access or influence it

**Comment by AEnterprise** [comment]
fixed b sponge

**Comment by kenijey** [comment]
uhm please let me know, is it fixed on latest sponge, or will fixed? cus i downloaded sponge 2347 but it still crashes

**Comment by AEnterprise** [comment]
see comment above: it is fixed on their end, for futher issues ask them and make sure you update spongeforge and sponge to the latest versions

**Comment by kenijey** [comment]
uh oh, i tried sponge 2348. it doesn't crash with only buildcraft, but in my modpack. it looks like same with the before crash report. but it doesn't crash if i delete buildcraft again. how can i know what causes? :/ 
please help :(
here is the crash report: 
[crash-2017-05-23_11.59.22-server.txt](https://github.com/BuildCraft/BuildCraft/files/1021549/crash-2017-05-23_11.59.22-server.txt)

**Comment by AEnterprise** [comment]
new crash but again it's a spongeforge problem, they are assuming that the world is a WorldServer but our fake world is just a regular world, please report it to them to get this fixed

as for knowing the cause of crashes: read the crashlogs

**Comment by kenijey** [comment]
oh, thanks a lot. i did by editing my latest comment on their side. hope be fixed..

**Comment by AEnterprise** [comment]
don't EVER do that, nobody gets a notification on github if you edit a comment so it will not be seen

**Comment by kenijey** [comment]
uhm but i just wrote that comment, i'm thinking they didn't read it yet. should i post new one?

**Comment by asiekierka** [comment]
Some people, like myself, check GitHub notifications primarily via email, so preferably yes.

**Comment by kenijey** [comment]
yeah i did.

**Comment by AEnterprise** [comment]
2h is also more then enough time to see, also things like github webooks integrating with discord and such (like we use) don't pick it up

**Comment by kenijey** [comment]
yeap, they reponed the issue. https://github.com/SpongePowered/SpongeForge/issues/1527#event-1094026263

**Comment by AEnterprise** [comment]
@kenijey please do not spam our issue tracker, if they pinged a BC team member there on an issue we are already folowing there is absolutely no need to also point at that

**Comment by kenijey** [comment]
hey ah, is it fixed in 7.99.4 ? thanks.

**Comment by AEnterprise** [comment]
no this isn't fixed yet, the issue needs work from both ends but the spongeforge team did not have time yet to look further into the issue
