### ISSUE TITLE
Extracting fluid from a block/machine containing multiple fluids causes the subsequent fluids to be deleted

### ISSUE THREAD

**Issue by JimmyAllnighter** [BuildCraft/BuildCraft#4094]
**BuildCraft version:** 7.99.15
**Forge version:** 14.23.2.2618 (Forge Mod Loader: 8.0.99.99)
**Link to crash report or log:** N/A
**Singleplayer or multiplayer:** Single, suspected multiplayer
**Steps to reproduce:** 

1. Set up a NuclearCraft Electrolyzer.

2. Connect a wood or wood-diamond extraction pipe (no filters) to the Electrolyzer and link it to a tank.

3. Activate the extraction pipe

4. Monitor the fluid levels in the Electrolyzer tanks GUI, as once the Hydrogen tanks empty, the deuterium tanks do so as well, however the Deuterium does not make it into the pipe - it gets deleted like Oxygen.

**Additional information:** When extracting from a NuclearCraft Electrolyzer (and probably other multi-tank blocks), fluids that are extracted after the first (in this case, Hydrogen), will be deleted (Deuterium, Oxygen). 

Here is a photo of the setup I used to reproduce this bug:

![2018-03-22_01 50 41](https://user-images.githubusercontent.com/36003168/37720689-83963abc-2d73-11e8-82b1-b7ba3f29c799.png)

**Comment by AEnterprise** [comment]
from investigation on discord:
works fine when use other mods to extract from the block so it's definatly the pipe messing up
trying to filter extract on the block doesn't work eighter, the block is either not exposing all fluids at once or pipe is not handeling multiple tanks with different fluids well for filtering

**Comment by AlexIIL** [comment]
Can you retry without using wooden-diamond pipes? (Just using normal, unfiltered, wooden pipes)

**Comment by turbodiesel4598** [comment]
I think I've fixed this on my side - the fluid-sensitive drain method was not checking to see if the fluid trying to be drained matched the one in the tank, and for some reason that seems to have caused this issue. [Here is a build with that change to test it out yourself if you'd like](https://www.dropbox.com/s/8y50rslx5gkaenu/NuclearCraft-2.9fSupaMegaBCFix%28Hopefully%29--1.12.2.jar?dl=0).

**Comment by JimmyAllnighter** [comment]
@AlexIIL I have tried with both and the bug persists/ed with both.

@turbodiesel4598 Thanks for patching that so quickly, I'll have to call it a night though because I'm rather true to my username. I'll have some feedback on this in ~15 hours

**Comment by AlexIIL** [comment]
Can you try with [7.99.16-pre3](https://mod-buildcraft.com/releases/testing/BuildCraft/7.99.16-pre3/buildcraft-7.99.16-pre3.jar) ? (NOTE: this is a prerelease, so some things will be even more buggy than normal!

**Comment by AlexIIL** [comment]
Thanks @turbodiesel4598, although it might be a good idea to change https://github.com/turbodiesel4598/NuclearCraft/blob/ae3c2c9ec13c0bd200a117bb4d21aaaa6117f2e1/src/main/java/nc/tile/energyFluid/TileEnergyFluid.java#L159-L167 to pass the resource directly to the internal tank, rather than just the amount. (At least, without testing further I think it might be useful - I don't know if your build already does this though).

**Comment by turbodiesel4598** [comment]
Ah yes, I'll get that fixed up too. And your new build works brilliantly - the wooden diamond pipe will now skip over the blacklisted fluids and only extract the allowed one :)
