### ISSUE TITLE
Item replacement when destroyed

### ISSUE THREAD

**Issue by Louuiss** [BuildCraft/BuildCraft#4110]
BuildCraft version: 7.99.15
Forge version: 14.23.2.2611
Link to crash report or log: -
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: place a striped pipe (the yellow and black one), and put an other one wich will destroyed the first one, when it detroyed it, the striped pipe became a void fluid pipe (the pipe who destroye fluids)
Additional information: 
I powered the striped pipe with creative engine.

**Comment by AEnterprise** [comment]
could you maybe provide some screenshots? i have no idea what exactly you are saying to make this bug heapen

**Comment by Louuiss** [comment]
The screenshots : 
    Before
[https://image.noelshack.com/fichiers/2018/14/2/1522775193-2018-04-03-19-04-58.png](url)
    After
[https://image.noelshack.com/fichiers/2018/14/2/1522775193-2018-04-03-19-04-13.png](url)

**Comment by AlexIIL** [comment]
This *might* have been fixed in 7.99.16 already. Can you try using [this prerelease](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.16-pre4/buildcraft-7.99.16-pre4.jar)?

**Comment by AEnterprise** [comment]
not realy, if a striped pipe breaks a pipe that pipe should be what comes out

**Comment by Louuiss** [comment]
With the release that axel told me, it happened what I've said. So the problem still exist except that it is not a pipe replacement now...
