### ISSUE TITLE
Quarry stops working if feeded with to much MJ

### ISSUE THREAD

**Issue by laeublit** [BuildCraft/BuildCraft#4169]
I power a quarry with EU over Energy Converter Mod (Addon to IC2)
If the converter get's feeded with 128 EU (equal 51 MJ) the quarry work's for a while and then hang up. It look's like the Drill get's out of the quarry range.

If I spread this 51 MJ to two quarry's everything works fine.

So I expect, that the quarry get's "overclocked" and in an undefined state with the full 51 MJ.

BuildCraft version: 7.99.15
Forge version: latest
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Power a quarry with 50+ MJ
Additional information: IC2 2-2.8.75, EnergyConverters_1.12.2-1.0.2.2 (with MJ enabled)

**Comment by AlexIIL** [comment]
Can you try updating to 7.99.17? (https://mod-buildcraft.com/pages/download.html) I think this might have been fixed since 7.99.15.

**Comment by laeublit** [comment]
Hi Alex

I just updated to the latest version (7.99.17), but I still get the same
behaviour of the quarry.

Attached is a screenshot about a "crazy" quarry. The top beam is moving out
of the defined quarry-range. The quarry doesn't break any blocks in this
state.

I hope to help you
Thomas


2018-05-18 17:49 GMT+02:00 AlexIIL <notifications@github.com>:

**Comment by rogermiranda1000** [comment]
Wait, just happened to me again and yes, the quarry arm goes out of range too.

**Comment by AlexIIL** [comment]
Ok, can you screenshot they quarry and the F3+debug information for it? (Either be in creative or give yourself the "Debugger" item and look at the quarry in F3 debug mode)

**Comment by rogermiranda1000** [comment]
![2018-12-29_16 57 37](https://user-images.githubusercontent.com/30045337/50541954-5124e480-0bb1-11e9-94f0-7780456bb276.png)
![2018-12-29_21 31 27](https://user-images.githubusercontent.com/30045337/50541955-51bd7b00-0bb1-11e9-93af-2e2b7ef9ce7b.png)
![2018-12-29_21 31 33](https://user-images.githubusercontent.com/30045337/50541956-51bd7b00-0bb1-11e9-8fcc-344f8de2c645.png)
![2018-12-29_21 31 47](https://user-images.githubusercontent.com/30045337/50541957-51bd7b00-0bb1-11e9-9e95-18efd7fd53b8.png)
OK, now I try the debug.

**Comment by rogermiranda1000** [comment]
I broke it, so I waited until it stops again. This time the arm is OK (when it goes out of range produces A LOT of lag).
![2018-12-29_21 37 47](https://user-images.githubusercontent.com/30045337/50542037-a9a8b180-0bb2-11e9-9cb1-f24f153253bf.png)
![2018-12-29_21 37 57](https://user-images.githubusercontent.com/30045337/50542038-a9a8b180-0bb2-11e9-8c45-2ec85257982f.png)
![2018-12-29_21 40 24](https://user-images.githubusercontent.com/30045337/50542039-aa414800-0bb2-11e9-81bb-4a88ec75fa3b.png)
![2018-12-29_21 40 39](https://user-images.githubusercontent.com/30045337/50542040-aa414800-0bb2-11e9-842f-5a688705ac01.png)
![2018-12-29_21 40 49](https://user-images.githubusercontent.com/30045337/50542041-aad9de80-0bb2-11e9-9d8c-c6329ff81ebf.png)

PD: Will the green thing go away?

**Comment by AlexIIL** [comment]
I don't know what the green thing is so it's probably a bug in something

**Comment by rogermiranda1000** [comment]
In the 2 firsts photos the quarry is working just fine.

**Comment by AlexIIL** [comment]
Oh ok so maybe I just never fixed the bug originally. Either way can you try reducing the number of engines? At the moment the quarry maxes out at about 30 MJ/t.

**Comment by rogermiranda1000** [comment]
When I used the debugger (right click on the quarry) the mining chunks lighted green, that's the green thing.

**Comment by Roodypoo0123** [comment]
Hello,

I'm using 7.99.19 along with the latest IC2 so setup the usual Consumer/bridge/Producer to translate EU to MJ. If I use kinetic pipe between the Producer and the quarry, while the energy is maximal (Pipe is showing full blue energy transit), the quarry stop at some point like it fried.
However if I put the Producer block right next to the quarry without any kinetics, the quarry is fine.

I have not seen the arm go out of range while the sudden stop happened on 3 different quarry in the same setup Producer > Kinetic pipe > Quarry.

**Comment by TxMat** [comment]
Hey,

I'm reviving this issue, I'm using the 7.99.24.1 ver and this bug is still a thing!
I was doing some benchmark to see what power I need to give to the quarry for it to mine in an optimal way but by giving it too much power it just breaks after a while.

I'm using an RF energy cube, which is then converted to EU directly in a bunch of forestry EU to RF motors converted into kinetic energy. 

it takes ~500 eu/t which is 1980 rf/t which is 198 MJ/t witch is WAY ABOVE the Limit of 30 MJ/t but I never saw this limit in-game 

also when it stops if you break the block where the quarry is stuck the arm just flies 100 blocks away from the range of the quarry.

(here is a screenshot)

![image](https://user-images.githubusercontent.com/46858765/124285350-21724100-db4e-11eb-9251-13c7a118eeb2.png)

if you want any details I'm here.
Have a nice day and thanks for this mod :).

**Comment by AlexIIL** [comment]
Can you try updating to [7.99.24.8](https://mod-buildcraft.com/buildcraft-799248.html)? 7.99.24.1 was released 6 months before that, so I might have forgotten to update this issue, since i think this has been fixed since then?
