### ISSUE TITLE
BuildCraft breaks CTM mod

### ISSUE THREAD

**Issue by seancrain** [BuildCraft/BuildCraft#4238]
BuildCraft version: 7.99.17
Forge version:  14.23.4.2739
Link to crash report or log: https://www.nosiphus.com/minecraft/crash-reports/latest.log
Singleplayer or multiplayer: both
Steps to reproduce: 
Download the following:
https://minecraft.curseforge.com/projects/ctm/files/2584026
https://bdcraft.net/downloads/purebdcraft-minecraft/#dl-112 - 128x
https://drive.google.com/uc?authuser=0&id=1eNCIwpAJSZ_LXvacb--F-3oSnHS8Yrr3&export=download
Additional information: CTM mod version 1.12.2-0.3.2.18

I put together a CTM patch for PureBDcraft a while ago. The patch does not have anything related to BuildCraft in it at all, and works normally when BC is not present:

![working](https://i.imgur.com/tQqIfRc.png)

However, if BuildCraft is added to the environment, this happens:

![not functional](https://i.imgur.com/l5ibFIw.png)

**Comment by AlexIIL** [comment]
I should it only the gold and iron blocks that don't work? Or do other blocks also not work?

**Comment by seancrain** [comment]
As far as I know, iron and gold are the only two that have rendering issues. What's funny is the diamond and emerald connected textures utilize the same method and work completely fine. So do the stained clay textures.

**Comment by seancrain** [comment]
Diamonds and emeralds started malfunctioning.

**Comment by AEnterprise** [comment]
can you provide a log from when this happens? maybe that has some clues on what is going on here

**Comment by seancrain** [comment]
@AEnterprise https://www.nosiphus.com/minecraft/crash-reports/latest-2.log

**Comment by seancrain** [comment]
So, I decided to revisit the issue, and I loaded an environment with Forge 2749, BuildCraft 7.99.17, BuildCraft Compat 7.99.14, and CTM-MC1.12.2-0.3.2.18.

This was the result:

![All four of them](https://i.imgur.com/L9TiE7r.png)

I disabled Animated Sprites and the OptiFine performance fix option, thinking it may have also conflicted with CTM somehow, but that did not solve the problem. Emerald blocks also use the same method as diamond, and yet one works and the other doesn't.

Any heads up on what's been going on since I was last here?

**Comment by AlexIIL** [comment]
I think this might be todo with that fact that buildcraft gates depend on a few of the vanilla textures for the gate edges: https://github.com/BuildCraft/BuildCraft/blob/8.0.x/buildcraft_resources/assets/buildcraftsilicon/models/plugs/gate.json.

To test this can you either (a) make a resource pack with that json file changed to use different textures or (b) rename the "gate.json" file in the BC jar file to "gate.json.backup" to see if removing it fixes the issue?

**Comment by seancrain** [comment]
That corrected the issue for diamond and iron, but gold remains broken. I will create overrides for that file as part of the patch.

**Comment by seancrain** [comment]
Edit: I found the other file (it was stripes.json in the buildcrafttransport folder), and I have fixed the issue.

**Comment by AlexIIL** [comment]
No, it's still an issue, that was just to see if that causes it.

**Comment by AlexIIL** [comment]
Erm, how specifically are you fixing it? Are you replacing the texture, or so you create a separate texture specifically for CTM?

**Comment by seancrain** [comment]
I was unsure over whether to close it either. Here's how I fixed the file.

I first took the non-CTM textures and placed them into a subfolder. I am unsure of how this falls under the BDcraft license, while the addon itself is okay, I already had a discussion with HanFox, the lead moderator of the forum, I sent a private message to him just a few minutes ago about the workaround.

Then, I took the problematic JSON files, added the subfolder directory to their texture mappings and then included them as overrides in the patch. While it does correct the problem on the surface, the underlying issue remains, it's just that the remapped files don't direct to problem-causing files.

I think what might be happening is that when it tries to load the base texture from its original location, it sees the JSON file directing the CTM mod to load the connected textures. Since BC doesn't support the CTM api, it gets confused and therefore neither mod will load the correct texture. That's my theory, it's likely not correct at all.

You might want to talk to @tterrag1098 for more information about this problem.

**Comment by tterrag1098** [comment]
Does this still occur?

**Comment by seancrain** [comment]
I haven't the slightest idea whether this still happens. I returned to using OptiFine months ago.
