### ISSUE TITLE
Fluid pipe seem to randomly disconnect

### ISSUE THREAD

**Issue by jakubg1** [BuildCraft/BuildCraft#4345]
BuildCraft version: 7.99.21
Forge version: 14.23.5.2808
Link to crash report or log: {none given}
Singleplayer or multiplayer: Singleplayer with LAN (host; the bug occurs also when without LAN though)

**Description:**
I've encountered a strange bug when placing a pipe network between the base and the nearest oil geyser. I've connected them by golden pipes along with the yellow wire to control mining. The pipes seem to randomly disconnect (probably when loading/unloading chunks?), and it wouldn't be a problem, when the wire would still behave normally, but the power in it is stopped and I can't control the mine. I didn't check if it does same to fluids flowing in it. Neither block update nor reloading the world (the game crashed once when I was trying to do it) removes the problem, I need to remove the pipe completely and re-place it again, but it's pointless because the bug occurs again after a while.

Screenshot:
![obraz](https://user-images.githubusercontent.com/24206305/52084016-5a82e180-25a1-11e9-9e75-38d908062cf2.png)

Steps to reproduce: 
I think the only need is an about 200 blocks long pipe along with a wire. Go away some blocks, then go back again.

Additional information:
I can provide them when asked.

Mod list: 

MCP 9.42 Powered by Forge 14.23.5.2808 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State  | ID                  | Version      | Source                        | Signature                                |
|:------ |:------------------- |:------------ |:----------------------------- |:---------------------------------------- |
| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                 | None                                     |
| LCHIJA | mcp                 | 9.42         | minecraft.jar                 | None                                     |
| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2808.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | forge               | 14.23.5.2808 | forge-1.12.2-14.23.5.2808.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | buildcraftlib       | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |
| LCHIJA | buildcraftcore      | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |
| LCHIJA | buildcraftbuilders  | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |
| LCHIJA | buildcrafttransport | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |
| LCHIJA | buildcraftsilicon   | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |
| LCHIJA | buildcraftcompat    | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |
| LCHIJA | buildcraftenergy    | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |
| LCHIJA | buildcraftfactory   | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |
| LCHIJA | buildcraftrobotics  | 7.99.21      | buildcraft-all-7.99.21.jar    | None                                     |

**Edit:**
Yes, it has to have something with chunks:
![obraz](https://user-images.githubusercontent.com/24206305/52085506-fb26d080-25a4-11e9-8155-6f2a4a945f00.png)
Probably the wrong way how the pipe connections are stored.

**Comment by flyingyalie** [comment]
BuildCraft version: 7.99.22
Forge version: 14.23.5.2780

I also had this problem, but I only needed a pipe run of about 40 blocks with blue pipe wire to make it happen. Also occurred on chunk boundaries like the op, so i've been able to stop it from happening with chunk loaders.

**Comment by AlexIIL** [comment]
I'm hoping that I fixed this alongside #4359 in https://github.com/BuildCraft/BuildCraft/commit/ab70f2c8bd9dc6222be56634f4bbbb4f53adf963 however I haven't replicated this inside a dev environment so I'm not sure. Can you try using [7.99.23-pre1](https://mod-buildcraft.com/pages/tests.html) to see if that stops the issue from occurring?

**Comment by flyingyalie** [comment]
Still having the same issue with blue and red pipe wire, but not with yellow of equal pipe runs. It seems to happen anytime the server restarts, regardless of whether or not there are chunk loaders.

**Comment by AlexIIL** [comment]
Ok, I actually replicated this in dev and it should be fully fixed now for 7.99.23.
